[package]
name = "server"
version = "0.1.0"
authors = ["GiantCowFilms <git@giantcowfilms.com>"]
edition = "2018"

[dependencies]
tokio = { version = "=0.1.19", features = ["async-await-preview"]}
tokio-tungstenite = "*"
serde_json = "1.0.36"
serde = { version = "1.0.85", features = ["rc"]}
serde_derive = "1.0.85"
futures = "0.1.25"
rand = { git = "https://github.com/rust-random/rand" }