[package]
name = "server"
version = "0.1.0"
authors = ["GiantCowFilms <git@giantcowfilms.com>"]
edition = "2018"

[dependencies]
tokio = "0.1.14"
ws = "0.7.9"
serde_json = "1.0.36"
serde = "1.0.85"
serde_derive = "1.0.85"
