name: Deploy Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Set Rust Override
      run: rustup override set nightly-2019-04-20
    - name: Build Server
      run: cargo build --verbose --release
    - name: Create Key File
      run: touch ~/key_file
    - name: Save Server Key
      run: echo "${{ secrets.SERVER_SSH_KEY }}"  > ~/key_file & chmod 400 ~/key_file
    # - name: Create Directory
    #   run: ssh github_actions@${{ secrets.SERVER_IP }} -o "StrictHostKeyChecking=no" -i ~/key_file -t "mkdir -p ${{ secrets.SERVER_DIRECTORY }}/server"
    - name: Upload
      run: scp -o "StrictHostKeyChecking=no" -i ~/key_file target/release/ipg_server github_actions@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DIRECTORY }}/server
  