name: Deploy Server

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-20.04 # This needs to match the host version's OS
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-musl
    - name: Build Server
      run: cargo build -p ipg_server --verbose --release --target x86_64-unknown-linux-musl
    - name: Create Key File
      run: touch ~/key_file
    - name: Save Server Key
      run: echo "${{ secrets.SERVER_SSH_KEY }}"  > ~/key_file & chmod 400 ~/key_file
    # - name: Create Directory
    #   run: ssh github_actions@${{ secrets.SERVER_IP }} -o "StrictHostKeyChecking=no" -i ~/key_file -t "mkdir -p ${{ secrets.SERVER_DIRECTORY }}/server"
    - name: Stop Server
      run: ssh github_actions@${{ secrets.SERVER_IP }}  -o "StrictHostKeyChecking=no" -i ~/key_file -tt "sudo systemctl stop ipg_server.service"
    - name: Upload
      run: scp -o "StrictHostKeyChecking=no" -i ~/key_file target/x86_64-unknown-linux-musl/release/ipg_server github_actions@${{ secrets.SERVER_IP }}:${{secrets.SERVER_DIRECTORY }}/server
    - name: Start Server
      run: ssh github_actions@${{ secrets.SERVER_IP }}  -o "StrictHostKeyChecking=no" -i ~/key_file -tt "sudo systemctl start ipg_server.service"
  